name: push-build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node_version: ${{ matrix.node-version }}

      - name: install dependencies on client
        working-directory: ./client
        run: yarn install

      - name: install dependencies on server
        working-directory: ./server
        run: yarn install

      - name: build application
        run: |
          yarn lint
          yarn test
          yarn build